[project]
name = "browse4j"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.11.1",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "pyinstaller>=6.20.0",
    "pylint>=4.0.5",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.14",
]

# Ruff
[tool.ruff]
src = ["src", "tests"]
exclude = ["src/ui/designer"]
line-length = 100
target-version="py313"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "N"]

[tool.ruff.format]
quote-style = "double"

# Mypy
[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
mypy_path = "src"
explicit_package_bases = true
files = ["src/"]
exclude = "src/ui/designer/.*"

# Désactiver tous les checks pour le dossier généré
[[tool.mypy.overrides]]
module = "ui.designer.*"
ignore_errors = true

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = [
    "--cov=lib",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov",
    "--cov-report=xml:coverage.xml",
    "--cov-fail-under=80",
]

[tool.coverage.run]
source = ["src/lib"]
branch = true
exclude = ["src/ui/designer"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "def __repr__",
]
